#!/bin/sh /etc/rc.common

START=98
STOP=15
USE_PROCD=1

SERVICE_NAME="passwall-snell"
LAUNCHER="/usr/share/passwall-snell/launcher.sh"

start_service() {
	local enabled

	config_load passwall_snell
	config_get_bool enabled main enabled 0
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$LAUNCHER"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param limits nofile="65535 65535"
	procd_close_instance
}

stop_service() {
	rm -f /var/run/passwall-snell.pid
}

service_triggers() {
	procd_add_reload_trigger passwall_snell
}
