#!/bin/sh

if [ -z "$IPKG_INSTROOT" ]; then
	/usr/share/passwall-snell/sync-passwall.sh cleanup >/dev/null 2>&1 || true
	/etc/init.d/passwall restart >/dev/null 2>&1 || true
	/etc/init.d/passwall-snell stop >/dev/null 2>&1 || true
	/etc/init.d/passwall-snell disable >/dev/null 2>&1 || true
fi
exit 0
